### ISSUE TITLE
Colour map `KeyError` when creating dendrogram.

### ISSUE THREAD

**Issue by darcyabjones** [ccdmb/BioDendro#17]
A user (Arshad Ali Shaikh from Canada) reported an issue via email regarding newer versions of scipy (>1.4.1) not supporting the colour scheme we're using.
Below is the error I found when attempting to run our test dataset.

```
$ BioDendro --results-dir results Fireflies_MSMS.mgf Fireflies_feature_list.txt

Running BioDendro v0.0.1

- input mgf file = Fireflies_MSMS.mgf
- input components file = Fireflies_feature_list.txt
- neutral = False
- cutoff = 0.6
- bin_threshold = 0.0008
- clustering_method = jaccard
- output processed file = results/processed.xlsx
- output results directory = results
- output html dendrogram = results/simple_dendrogram.html
- dendrogram figure width = 900
- dendrogram figure height = 1200
- scaling = False
- filtering = False
- eps = 0.6
- mz_tolerance = 0.002
- retention_tolerance = 5


Processing inputs
Binning and clustering
This may take some time...
Writing per-cluster summaries

Writing output html dendrogram
Traceback (most recent call last):
  File "/home/darcy/BioDendro/env/bin/BioDendro", line 11, in <module>
    load_entry_point('BioDendro', 'console_scripts', 'BioDendro')()
  File "/home/darcy/BioDendro/BioDendro/__init__.py", line 383, in main
    pipeline(
  File "/home/darcy/BioDendro/BioDendro/__init__.py", line 231, in pipeline
    _ = tree.plot(
  File "/home/darcy/BioDendro/BioDendro/cluster.py", line 412, in plot
    dendro = dendrogram(
  File "/home/darcy/BioDendro/BioDendro/plot.py", line 41, in dendrogram
    (dd_traces, xvals, yvals, ordered_labels, leaves) = _get_traces(
  File "/home/darcy/BioDendro/BioDendro/plot.py", line 243, in _get_traces
    colors = [color_map[k] for k in dendro["color_list"]]
  File "/home/darcy/BioDendro/BioDendro/plot.py", line 243, in <listcomp>
    colors = [color_map[k] for k in dendro["color_list"]]
KeyError: 'C0'
```

I just need to update the colour map it seems.

**Comment by darcyabjones** [comment]
This should be fixed with release `0.0.3`.
We're now using the matplotlib colour palettes.

I think Plotly has changed its aesthetics a bit.
The background is gray and it's a bit hard to see this particular plot.
